import os
import scipy as sp
from scipy import constants
from scipy import units
os.system("cls")

print(constants.liter)
print()
print(constants.litre)
print()

print(sp.__version__)
print()

print(constants.pi)
print()

print(dir(constants))
print()

print(constants.pebi)
print()
print(constants.zepto)
print()

# print(dir(units))
# print()

print(constants.yotta)
print()
print(constants.zetta)
print()
print(constants.exa)
print()
print(constants.peta)
print()
print(constants.tera)
print()
print(constants.giga)
print()
print(constants.mega)
print()
print(constants.kilo)
print()
print(constants.hecto)
print()
print(constants.deka)
print()
print(constants.deci)
print()
print(constants.centi)
print()
print(constants.milli)
print()
print(constants.micro)
print()
print(constants.nano)
print()
print(constants.pico)
print()
print(constants.femto)
print()
print(constants.atto)
print()
print(constants.zepto)