import os
import numpy as np
os.system("cls")

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[0])
print()

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1])
print()

arr = np.array([1, 2, 3, 4, 5, 6, 7])
for x in arr:
       print(arr)
print()

arr = np.array([1, 2, 3, 4, 5, 6, 7])
for x in arr:
       print(x)
print()

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[2]+arr[3])
print()

arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr)
print(arr.ndim)
print()
print(arr[0,0])
print()
print(arr[0,1])
print()
print(arr[0,2])
print()
print(arr[1,0])
print()
print(arr[1,1])
print()
print(arr[1,2])
print()

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr.ndim)
print()
print(arr[0,0,0])
print()
print(arr[0,0,1])
print()
print(arr[0,0,2])
print()
print(arr[1,0,1])
print()
print(arr[1,1,1])
print()
print(arr[1,1,2])
print()

arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr)
print(arr.ndim)
print()
print(arr[-1,-1])
print()
print(arr[-1,-2])
print()
print(arr[-1,-3])
print()
print(arr[-2,-1])
print()
print(arr[-2,-2])
print()
print(arr[-2,-3])